project:
  type: website
  output-dir: docs 

website:
  title: "Data Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/urbainm
format:
  html:
    page-layout: full
    theme:
      - sandstone
    css: styles.css



